name: Job Summary Demo
on: [push]
jobs:
  run_job_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Job Summary
        run: |
          ls ${{ github.workspace }}
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
